<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Lab1MVCApp_Sanchez</RootNamespace>
    <AssemblyName>Lab1MVCApp_Sanchez</AssemblyName>
  </PropertyGroup>

</Project>
